// import type { Metadata } from 'next'
import { Baloo_2, Roboto } from '@next/font/google'
import './globals.css'
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const baloo = Baloo_2({
  subsets: ['latin'],
  variable: '--font-baloo',
})

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['300', '700'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className={`${baloo.variable} ${roboto.variable}`}>
      <body>{children}</body>
    </html>
  )
}
